/** Weather-effects proxy. */
import { fetchRegionalWeather, validRegionalPoint } from './regionalBrief.mjs';
import { clientKey, coalesceProxyRequest, makeRateLimiter } from '../shared.mjs';
const CACHE_MS = 5 * 60_000, STALE_MS = 30 * 60_000, MAX_CACHE = 180;
const cache = new Map(), inFlight = new Map(), rateLimiter = makeRateLimiter({ windowMs: 60_000, max: 45, globalMax: 120 });
function trimCache() { while (cache.size > MAX_CACHE) cache.delete(cache.keys().next().value); }
export function weatherEffectsProxy() {
  async function refresh(point, key) { const weather = await fetchRegionalWeather(point); if (!weather) throw new Error('Weather observation unavailable'); const payload = { status: 'ready', retrievedAt: new Date().toISOString(), coordinates: point, weather }; cache.set(key, { payload, cachedAt: Date.now() }); trimCache(); return payload; }
  return { name: 'weather-effects-proxy', configureServer(server) { server.middlewares.use('/api/weather-effects', async (req, res) => { if (req.method !== 'GET') { res.writeHead(405, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ error: 'Method Not Allowed' })); return; } if (!rateLimiter(clientKey(req))) { res.writeHead(429, { 'Content-Type': 'application/json', 'Retry-After': '10' }); res.end(JSON.stringify({ error: 'Rate limit exceeded' })); return; } const point = validRegionalPoint(new URL(req.url || '', 'http://localhost').searchParams); if (!point) { res.writeHead(400, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ error: 'Valid latitude and longitude are required' })); return; } const key = `${(Math.round(point.latitude * 10) / 10).toFixed(1)},${(Math.round(point.longitude * 10) / 10).toFixed(1)}`, now = Date.now(), cached = cache.get(key); if (cached && now - cached.cachedAt <= CACHE_MS) { res.writeHead(200, { 'Content-Type': 'application/json', 'Cache-Control': 'public, max-age=60', 'X-Weather-Effects': 'HIT' }); res.end(JSON.stringify({ ...cached.payload, status: 'cached' })); return; } const request = coalesceProxyRequest(inFlight, key, () => refresh(point, key)); try { const payload = await request.promise; res.writeHead(200, { 'Content-Type': 'application/json', 'Cache-Control': 'public, max-age=60', 'X-Weather-Effects': request.shared ? 'INFLIGHT' : 'MISS' }); res.end(JSON.stringify(payload)); } catch { if (cached && now - cached.cachedAt <= STALE_MS) { res.writeHead(200, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store', 'X-Weather-Effects': 'STALE' }); res.end(JSON.stringify({ ...cached.payload, status: 'stale' })); return; } res.writeHead(503, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }); res.end(JSON.stringify({ error: 'Weather effects are temporarily unavailable' })); } }); } };
}
